[meta]
name     = "HuntHelper"
author   = "tboby"
category = "Testing"
version  = "0.0.1"

[script]
dependencies = [ "NadeoServices", "VehicleState", "PlayerState", "MLHook", "MLFeedRaceData" ]
optional_dependencies = [ "ChampionMedals", "SBVilleCampaignChallenges" ]